/**
 * Spoken-phrase delivery for the audio variant of « Langues ».
 *
 * Clips are generated by scripts/gen_language_audio.mjs and served from the
 * public `game-audio` Supabase Storage bucket — NOT bundled: 310 files would add
 * ~8 MB to an app that already ships ~12 MB of assets, and every corrected
 * phrase would need a new store build.
 *
 * Paths are content-addressed (`<id>.<hash of the text>.mp3`), which makes every
 * cache self-invalidating: fixing a typo in the corpus changes the file name, so
 * no stale clip can survive on disk, in the CDN or in the browser cache. That is
 * what lets the uploads set a one-year Cache-Control.
 *
 * Mirrors src/lib/flags.ts (remote asset + warm-up), with an on-disk cache on
 * top since clips are far heavier than flag images.
 */
import { Platform } from 'react-native';
import * as FileSystem from 'expo-file-system/legacy';

import { LANGUAGES_CORPUS_VERSION, type LanguagePhrase } from '../data/languages';
import { log } from './log';

const BUCKET = 'game-audio';
const BASE = `${process.env.EXPO_PUBLIC_SUPABASE_URL ?? ''}/storage/v1/object/public/${BUCKET}`;

/**
 * Where cached clips live, resolved lazily: `cacheDirectory` is null on web and
 * can still be unset at import time on native. Evictable by the OS, by design —
 * a purged clip simply streams again.
 */
function cacheDir(): string | null {
  const base = FileSystem.cacheDirectory;
  return base ? `${base}langaudio/` : null;
}

/**
 * 32-bit FNV-1a — byte for byte the hash used by daily.ts / league.ts, and
 * re-implemented identically in scripts/gen_language_audio.mjs. If the two ever
 * disagree, every clip becomes unreachable at once, so languageAudio.test.ts
 * pins a regression vector.
 */
export function fnv1a32(s: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

/** The content hash that suffixes a clip's file name. */
export function phraseHash(text: string): string {
  return fnv1a32(text).toString(16).padStart(8, '0');
}

/** `<code>/<id>.<hash8>.mp3` — the path inside the versioned folder. */
export function phraseAudioPath(code: string, phrase: LanguagePhrase): string {
  return `languages/v${LANGUAGES_CORPUS_VERSION}/${code}/${phrase.id}.${phraseHash(phrase.text)}.mp3`;
}

/** Public URL of a clip. */
export function phraseAudioUrl(code: string, phrase: LanguagePhrase): string {
  return `${BASE}/${phraseAudioPath(code, phrase)}`;
}

/** Flat local file name (the path's slashes collapsed). */
function localName(code: string, phrase: LanguagePhrase): string {
  return phraseAudioPath(code, phrase).replace(/\//g, '_');
}

let dirReady: Promise<void> | null = null;
function ensureDir(dir: string): Promise<void> {
  if (!dirReady) {
    dirReady = FileSystem.makeDirectoryAsync(dir, { intermediates: true }).catch(() => {});
  }
  return dirReady;
}

/** In-flight/settled downloads, so a prefetch and a play never race. */
const inFlight = new Map<string, Promise<string>>();

/**
 * A playable URI for a phrase: the cached file when possible, the remote URL
 * otherwise. NEVER throws and never returns null — a failed download falls back
 * to streaming, and the caller decides (after retries) whether to degrade the
 * question to text.
 */
export async function ensureCached(code: string, phrase: LanguagePhrase): Promise<string> {
  const url = phraseAudioUrl(code, phrase);
  const dir = cacheDir();
  // Web has no FileSystem; the HTTP cache plus the one-year Cache-Control on the
  // objects already make the second play free.
  if (Platform.OS === 'web' || !dir) return url;

  const key = localName(code, phrase);
  const existing = inFlight.get(key);
  if (existing) return existing;

  const task = (async () => {
    const target = `${dir}${key}`;
    try {
      await ensureDir(dir);
      const info = await FileSystem.getInfoAsync(target);
      if (info.exists && (info.size ?? 0) > 0) return target;
      const res = await FileSystem.downloadAsync(url, target);
      if (res.status >= 400) throw new Error(`HTTP ${res.status}`);
      return res.uri;
    } catch (e) {
      // Drop it so a later attempt can retry, and stream in the meantime.
      inFlight.delete(key);
      log.debug('language audio cache miss', e);
      return url;
    }
  })();

  inFlight.set(key, task);
  return task;
}

/**
 * Warm the cache for an upcoming run. Fire-and-forget and deliberately
 * sequential-ish (two at a time): a whole round is only ~150 KB, and hammering
 * the network on a mobile connection delays the clip actually being played.
 */
export function prefetchPhrases(items: { code: string; phrase: LanguagePhrase }[]): void {
  let at = 0;
  const pump = () => {
    if (at >= items.length) return;
    const { code, phrase } = items[at++];
    ensureCached(code, phrase).catch(() => {}).then(pump);
  };
  pump();
  pump();
}

/**
 * Delete cached clips that are no longer in the catalogue — a corrected phrase
 * changes its hash and would otherwise leave its old file behind forever.
 * Best-effort; called once when the mode opens.
 */
export async function pruneAudioCache(keep: Set<string>): Promise<void> {
  const dir = cacheDir();
  if (Platform.OS === 'web' || !dir) return;
  try {
    const info = await FileSystem.getInfoAsync(dir);
    if (!info.exists) return;
    const files = await FileSystem.readDirectoryAsync(dir);
    await Promise.all(
      files
        .filter((f) => !keep.has(f))
        .map((f) => FileSystem.deleteAsync(`${dir}${f}`, { idempotent: true }).catch(() => {})),
    );
  } catch (e) {
    log.debug('language audio prune failed', e);
  }
}

/** Every local file name the current catalogue can legitimately produce. */
export function cacheKeepSet(defs: { code: string; phrases: LanguagePhrase[] }[]): Set<string> {
  const keep = new Set<string>();
  for (const d of defs) for (const p of d.phrases) keep.add(localName(d.code, p));
  return keep;
}

/** Test hook: forget in-flight downloads. */
export function __resetAudioCache(): void {
  inFlight.clear();
  dirReady = null;
}
