import { StyleSheet } from 'react-native';

/**
 * Styles shared between the main menu and the classic game screen.
 * Light-mode variants are suffixed with `Light` and layered on top of the
 * dark (default) style.
 */
export const commonStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0f172a', userSelect: 'none' },
  containerLight: { backgroundColor: '#f8fafc' },
  header: {
    paddingHorizontal: 15,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#1e293b',
  },
  headerLight: { backgroundColor: '#fff', borderBottomColor: '#e2e8f0' },
  title: { fontSize: 20, fontWeight: '900', color: '#f8fafc' },
  titleLight: { color: '#1e293b' },
  headerStats: {
    flexDirection: 'row',
    backgroundColor: '#1e293b',
    borderRadius: 12,
    padding: 6,
    alignItems: 'center',
  },
  headerStatsLight: { backgroundColor: '#f1f5f9' },
  statBox: { paddingHorizontal: 8, alignItems: 'center' },
  statLabel: { fontSize: 8, color: '#64748b', fontWeight: 'bold', marginBottom: 2 },
  statLabelLight: { color: '#94a3b8' },
  statValue: { fontSize: 16, fontWeight: '900', color: '#f8fafc' },
  statValueLight: { color: '#1e293b' },
  statTotal: { fontSize: 10, color: '#475569', marginLeft: 2 },
  statDivider: { width: 1, height: 20, marginHorizontal: 4 },
  refreshBtn: {
    backgroundColor: '#1e293b',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#334155',
  },
  refreshBtnLight: { backgroundColor: '#fff', borderColor: '#e2e8f0' },
  countryCard: {
    backgroundColor: '#1e293b',
    borderRadius: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#334155',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  countryCardLight: { backgroundColor: '#fff', borderColor: '#e2e8f0', shadowOpacity: 0.05 },
  countryLabel: { fontSize: 10, fontWeight: 'bold', color: '#38bdf8', letterSpacing: 1 },
  countryFlag: { borderRadius: 8 },
  countryName: { fontWeight: '900', color: '#f8fafc', textAlign: 'center' },
  countryNameLight: { color: '#1e293b' },
  instruction: { color: '#64748b', fontWeight: '500' },
  themesGrid: { width: '100%' },
  themeCard: {
    backgroundColor: '#1e293b',
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#334155',
  },
  themeCardLight: { backgroundColor: '#fff', borderColor: '#e2e8f0' },
  usedThemeCard: { opacity: 0.4, backgroundColor: '#0f172a' },
  usedThemeCardLight: { opacity: 0.4, backgroundColor: '#f8fafc' },
  themeLabel: { fontWeight: 'bold', color: '#f8fafc' },
  themeLabelLight: { color: '#334155' },
  emoji: { marginRight: 10 },
  selectionInfo: { alignItems: 'flex-end' },
  selectionCountry: { color: '#64748b', fontWeight: 'bold' },
  selectionRank: { fontWeight: '900' },
  winCard: {
    backgroundColor: '#1e293b',
    borderRadius: 24,
    padding: 25,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#334155',
  },
  winCardLight: { backgroundColor: '#fff', borderColor: '#e2e8f0' },
  winTitle: { fontSize: 24, fontWeight: '900', color: '#f8fafc', marginTop: 15, marginBottom: 20 },
  winTitleLight: { color: '#1e293b' },
  summaryTotal: { alignItems: 'center', marginBottom: 30 },
  summaryTable: { width: '100%', gap: 10 },
  summaryHeader: { flexDirection: 'row', paddingHorizontal: 10, marginBottom: 5 },
  summaryHeaderText: { fontSize: 10, fontWeight: '900', color: '#475569' },
  summaryHeaderTextLight: { color: '#475569' },
  summaryRow: {
    flexDirection: 'row',
    backgroundColor: '#0f172a',
    padding: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  summaryRowLight: { backgroundColor: '#f8fafc' },
  rowThemeLabel: { fontSize: 13, fontWeight: 'bold', color: '#f8fafc' },
  rowThemeLabelLight: { color: '#1e293b' },
  rowCountryOptimal: { fontSize: 10, color: '#475569' },
  rowCountryOptimalLight: { color: '#475569' },
  rowRank: { fontSize: 16, fontWeight: '900' },
  rowRankOptimal: { fontSize: 10, color: '#475569' },
  playAgainBtn: {
    backgroundColor: '#10b981',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 30,
    width: '100%',
    justifyContent: 'center',
  },
  playAgainText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
});
