// Packs render_critters.py frames into one horizontal webp strip per critter
// (assets/story/critters/<key>.webp) + src/data/storyCritters.gen.ts.
//   node convert_critters.mjs <frames_dir>
// Every frame of a critter is cropped to the SAME box (union of the opaque
// pixels over the whole loop) so the animal never jitters inside its frame.
import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';

const HERE = path.dirname(new URL(import.meta.url).pathname);
const APP = path.dirname(HERE);
const FRAMES = process.argv[2] ?? path.join(HERE, 'out', 'critters');
const OUT = path.join(APP, 'assets', 'story', 'critters');
const STORE_H = 200; // stored frame height (shown at 45-100 logical px)
const MAX_W = 380;   // cap for long swimmers
fs.mkdirSync(OUT, { recursive: true });

/**
 * Seen through the water: colours pulled halfway to the sea blue, ink softened,
 * a touch of blur and 70 % opacity — the animal reads BELOW the surface.
 */
const SEA = [28, 118, 172];
async function underwater(buf) {
  const { data, info } = await sharp(buf).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  for (let i = 0; i < data.length; i += 4) {
    for (let c = 0; c < 3; c++) data[i + c] = Math.round(data[i + c] * 0.5 + SEA[c] * 0.5);
    data[i + 3] = Math.round(data[i + 3] * 0.7);
  }
  return sharp(data, { raw: info }).blur(0.9).png().toBuffer();
}

const table = JSON.parse(fs.readFileSync(path.join(HERE, 'critters.json'), 'utf8'));
const meta = {};
for (const [key, cfg] of Object.entries(table)) {
  if (key.startsWith('_')) continue;
  // A walker's idle strip (<key>_idle) is cropped with the SAME box as its
  // walk, so the app can swap them in place without the animal jumping.
  const keys = cfg.idle ? [key, `${key}_idle`] : [key];
  const sets = keys.map((k) => {
    const dir = path.join(FRAMES, k);
    return { k, dir, files: fs.readdirSync(dir).filter((f) => f.endsWith('.png')).sort() };
  });
  let x0 = Infinity, y0 = Infinity, x1 = -1, y1 = -1, W0 = 0, H0 = 0;
  for (const { dir, files } of sets) {
    for (const f of files) {
      const { data, info } = await sharp(path.join(dir, f)).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
      W0 = info.width; H0 = info.height;
      for (let y = 0; y < info.height; y++) {
        for (let x = 0; x < info.width; x++) {
          if (data[(y * info.width + x) * 4 + 3] > 10) {
            if (x < x0) x0 = x; if (x > x1) x1 = x; if (y < y0) y0 = y; if (y > y1) y1 = y;
          }
        }
      }
    }
  }
  const pad = 3;
  x0 = Math.max(0, x0 - pad); y0 = Math.max(0, y0 - pad);
  x1 = Math.min(W0 - 1, x1 + pad); y1 = Math.min(H0 - 1, y1 + pad);
  const cw = x1 - x0 + 1, ch = y1 - y0 + 1;
  let fh = STORE_H, fw = Math.round((cw / ch) * STORE_H);
  if (fw > MAX_W) { fw = MAX_W; fh = Math.round((ch / cw) * MAX_W); }
  for (const { k, dir, files } of sets) {
    const tiles = await Promise.all(files.map((f, i) =>
      sharp(path.join(dir, f)).extract({ left: x0, top: y0, width: cw, height: ch }).resize(fw, fh).png().toBuffer()
        .then((buf) => (cfg.underwater ? underwater(buf) : buf))
        .then((input) => ({ input, left: i * fw, top: 0 }))));
    await sharp({ create: { width: fw * files.length, height: fh, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } })
      .composite(tiles).webp({ quality: 82, alphaQuality: 90, effort: 6 }).toFile(path.join(OUT, `${k}.webp`));
    meta[k] = { frames: files.length, w: fw, h: fh };
    const kb = (fs.statSync(path.join(OUT, `${k}.webp`)).size / 1024).toFixed(0);
    console.log(`${k.padEnd(16)} ${files.length} × ${fw}×${fh}  ${kb} KB`);
  }
}

const lines = Object.entries(meta).map(([k, m]) =>
  `  ${k}: { src: require('../../assets/story/critters/${k}.webp'), frames: ${m.frames}, w: ${m.w}, h: ${m.h} },`);
fs.writeFileSync(path.join(APP, 'src', 'data', 'storyCritters.gen.ts'), `// GENERATED by asset-pipeline/convert_critters.mjs — do not edit.
// Pre-rendered 3D wildlife of the story map (Quaternius CC0 models, Cartoon HD
// toon + ink outline): one horizontal strip of \`frames\` frames of w×h px each.
/* eslint-disable @typescript-eslint/no-require-imports -- static Metro asset requires */

export interface CritterArt {
  src: number;
  frames: number;
  /** One frame's pixel size in the strip (aspect ratio source). */
  w: number;
  h: number;
}

export const CRITTER_ART = {
${lines.join('\n')}
} satisfies Record<string, CritterArt>;

export type CritterKey = keyof typeof CRITTER_ART;
`);
console.log('wrote src/data/storyCritters.gen.ts');
