// Régénère src/data/cosmeticLayers.gen.ts : map id cosmétique → require() des
// couches WebP pré-rendues (Metro exige des require statiques, d'où le codegen).
// Lancer via tsx : cd asset-pipeline && npm run manifest
import { existsSync, readdirSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

import { ALL_PARTS } from '../src/data/cosmetics';

const here = dirname(fileURLToPath(import.meta.url));
const assetsDir = join(here, '..', 'assets', 'cosmetics');
const outFile = join(here, '..', 'src', 'data', 'cosmeticLayers.gen.ts');

const files = new Set(existsSync(assetsDir) ? readdirSync(assetsDir).filter((f) => f.endsWith('.webp')) : []);

const entries = [];
for (const part of ALL_PARTS) {
  const main = `${part.id}.webp`;
  const back = `${part.id}_back.webp`;
  const front = `${part.id}_front.webp`;
  const sprite = `${part.id}_sprite.webp`;
  const fields = [];
  if (files.has(main)) fields.push(`main: require('../../assets/cosmetics/${main}')`);
  if (files.has(back)) fields.push(`back: require('../../assets/cosmetics/${back}')`);
  if (files.has(front)) fields.push(`front: require('../../assets/cosmetics/${front}')`);
  if (files.has(sprite)) fields.push(`sprite: require('../../assets/cosmetics/${sprite}')`);
  if (fields.length) entries.push(`  ${part.id}: { ${fields.join(', ')} },`);
}

const disable = entries.length ? '/* eslint-disable */\n' : '';
const body = `${disable}// GENERATED by asset-pipeline/gen_manifest.mjs — do not edit by hand.
// Régénérer après un rendu Blender : cd asset-pipeline && npm run manifest
// Chaque entrée référence les couches WebP pré-rendues d'un item du catalogue
// (main = couche unique ; back/front = anneaux passant derrière ET devant le globe).

export interface CosmeticLayerSources {
  main?: number;
  back?: number;
  front?: number;
  /** Tight solo render (live-preview sprite planted at real coordinates). */
  sprite?: number;
}

export const COSMETIC_LAYERS: Record<string, CosmeticLayerSources> = {
${entries.join('\n')}
};
`;

writeFileSync(outFile, body);
console.log(`cosmeticLayers.gen.ts : ${entries.length} entrées (${files.size} fichiers webp trouvés)`);
