// Footprints of the band scenery (out/story/props_<biome>.json, written by
// render_story_kit.py next to each band render) → src/data/storyBandProps.gen.ts,
// so the map's wildlife walks around trees, rocks and dunes instead of over them.
//   node gen_story_props.mjs
import fs from 'node:fs';
import path from 'node:path';

const HERE = path.dirname(new URL(import.meta.url).pathname);
const BIOMES = ['prairie', 'desert', 'volcan', 'glace', 'jungle', 'archipel', 'savane', 'cosmos'];
const MIN = 24; // px: grass tufts & pebbles are fine to walk past
const rows = BIOMES.map((b) => {
  const boxes = JSON.parse(fs.readFileSync(path.join(HERE, 'out/story', `props_${b}.json`), 'utf8'))
    .filter(([x0, y0, x1, y1]) => Math.max(x1 - x0, y1 - y0) >= MIN);
  return `  ${b}: [${boxes.map((q) => `[${q.join(', ')}]`).join(', ')}],`;
});
fs.writeFileSync(path.join(HERE, '..', 'src/data/storyBandProps.gen.ts'), `// GENERATED by asset-pipeline/gen_story_props.mjs — do not edit.
// Top-down footprint of each baked prop in the band art, in art px (390×1180,
// y down from the band image top): [x0, y0, x1, y1].

export const BAND_OBSTACLES: Record<string, readonly (readonly [number, number, number, number])[]> = {
${rows.join('\n')}
};
`);
console.log('wrote storyBandProps.gen.ts');
