// Textures globes 4096×2048 (webp) + manifest des assets 3D de la preview live.
//   cd asset-pipeline && node gen_models_manifest.mjs
// - textures_globe/<style>.png -> ../assets/globes/globe_<style>.webp
// - scanne ../assets/models3d/*.glb
// - écrit src/data/cosmeticModels.gen.ts (require maps Metro)
import { mkdirSync, readdirSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import sharp from 'sharp';

const here = dirname(fileURLToPath(import.meta.url));
const texSrc = join(here, 'textures_globe');
const texDst = join(here, '..', 'assets', 'globes');
const glbDir = join(here, '..', 'assets', 'models3d');
const outTs = join(here, '..', 'src', 'data', 'cosmeticModels.gen.ts');

mkdirSync(texDst, { recursive: true });
const styles = [];
for (const f of readdirSync(texSrc).filter((f) => f.endsWith('.png')).sort()) {
  const style = f.replace('.png', '');
  // Native render size, no downscale: these textures are no longer only worn by
  // a 200 px avatar — the gameplay globe zooms up to 24×, and 1024×512 turned to
  // mush as soon as the player went hunting for a small country. Flat vector art
  // compresses well, so quality 76 buys the resolution back at ~220 KB each.
  await sharp(join(texSrc, f)).webp({ quality: 76 }).toFile(
    join(texDst, `globe_${style}.webp`));
  styles.push(style);
}

const models = readdirSync(glbDir).filter((f) => f.endsWith('.glb')).sort()
  .map((f) => f.replace('.glb', ''));

const lines = [
  '/* eslint-disable */',
  '// GENERATED by asset-pipeline/gen_models_manifest.mjs — do not edit by hand.',
  '// Assets 3D de la preview avatar live : modèles GLB du rig (emblèmes,',
  '// satellites, orbites) + textures équirect cartoon des styles de globe.',
  '',
  'export const COSMETIC_MODELS: Record<string, number> = {',
  ...models.map((id) => `  ${id}: require('../../assets/models3d/${id}.glb'),`),
  '};',
  '',
  'export const GLOBE_TEXTURES: Record<string, number> = {',
  ...styles.map((s) => `  ${s}: require('../../assets/globes/globe_${s}.webp'),`),
  '};',
  '',
];
writeFileSync(outTs, lines.join('\n'));
console.log(`cosmeticModels.gen.ts : ${models.length} GLB + ${styles.length} textures globes`);
