// Vendorise three.js en IIFE minifié dans src/vendor/threeSource.ts.
// La chaîne est splicée telle quelle dans les HTML injectés en WebView/iframe
// (même mécanique que les polygones) : offline garanti, aucun CDN.
//   cd asset-pipeline && npm run vendor:three
import { build } from 'esbuild';
import { mkdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const here = dirname(fileURLToPath(import.meta.url));
const threeVersion = JSON.parse(
  readFileSync(join(here, 'node_modules', 'three', 'package.json'), 'utf8'),
).version;

const result = await build({
  stdin: {
    contents:
      "export * from 'three';\n" +
      "export { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';",
    resolveDir: here,
  },
  bundle: true,
  minify: true,
  format: 'iife',
  globalName: 'THREE',
  target: ['es2020'],
  write: false,
  legalComments: 'none',
});

const code = result.outputFiles[0].text;
const outDir = join(here, '..', 'src', 'vendor');
mkdirSync(outDir, { recursive: true });
const header =
  '/* eslint-disable */\n' +
  '// GENERATED by asset-pipeline/vendor-three.mjs — do not edit.\n' +
  `// three.js r${threeVersion}, bundle IIFE minifié (globalName THREE), licence MIT.\n` +
  '// Régénérer : cd asset-pipeline && npm run vendor:three\n';
writeFileSync(
  join(outDir, 'threeSource.ts'),
  `${header}export const THREE_VERSION = ${JSON.stringify(threeVersion)};\nexport const THREE_SRC: string = ${JSON.stringify(code)};\n`,
);
console.log(`threeSource.ts écrit (${(code.length / 1024).toFixed(0)} KB, three r${threeVersion})`);
