/* AUTO-GENERATED by scripts/build_region_data.mjs — do not edit. */
import manifest from './manifest.json';

export interface Region { id: string; name: string; name_en: string; lat: number; lng: number; r: number[][][]; }
export interface RegionFile { country: string; level: string; name: string; name_en: string; unit?: string | null; regions: Region[]; }
export interface RegionLevel { key: string; count: number; }
export interface RegionCountry { cca3: string; name: string; name_en: string; unit?: string | null; levels: RegionLevel[]; }

import r0 from './ARG.json';
import r1 from './AUS.json';
import r2 from './AUT.json';
import r3 from './BEL.json';
import r4 from './BRA.json';
import r5 from './CAN.json';
import r6 from './CHE.json';
import r7 from './CHL.json';
import r8 from './CHN.json';
import r9 from './COL.json';
import r10 from './DEU.json';
import r11 from './EGY.json';
import r12 from './ESP.json';
import r13 from './FRA.json';
import r14 from './FRA-departments.json';
import r15 from './GRC.json';
import r16 from './IDN.json';
import r17 from './IND.json';
import r18 from './ITA.json';
import r19 from './JPN.json';
import r20 from './MAR.json';
import r21 from './MEX.json';
import r22 from './NGA.json';
import r23 from './NLD.json';
import r24 from './NOR.json';
import r25 from './POL.json';
import r26 from './PRT.json';
import r27 from './RUS.json';
import r28 from './SWE.json';
import r29 from './TUR.json';
import r30 from './USA.json';
import r31 from './ZAF.json';

export const REGION_MANIFEST = manifest as unknown as RegionCountry[];

export const BUNDLED_REGIONS: Record<string, RegionFile> = {
  'ARG': r0 as unknown as RegionFile,
  'AUS': r1 as unknown as RegionFile,
  'AUT': r2 as unknown as RegionFile,
  'BEL': r3 as unknown as RegionFile,
  'BRA': r4 as unknown as RegionFile,
  'CAN': r5 as unknown as RegionFile,
  'CHE': r6 as unknown as RegionFile,
  'CHL': r7 as unknown as RegionFile,
  'CHN': r8 as unknown as RegionFile,
  'COL': r9 as unknown as RegionFile,
  'DEU': r10 as unknown as RegionFile,
  'EGY': r11 as unknown as RegionFile,
  'ESP': r12 as unknown as RegionFile,
  'FRA': r13 as unknown as RegionFile,
  'FRA-departments': r14 as unknown as RegionFile,
  'GRC': r15 as unknown as RegionFile,
  'IDN': r16 as unknown as RegionFile,
  'IND': r17 as unknown as RegionFile,
  'ITA': r18 as unknown as RegionFile,
  'JPN': r19 as unknown as RegionFile,
  'MAR': r20 as unknown as RegionFile,
  'MEX': r21 as unknown as RegionFile,
  'NGA': r22 as unknown as RegionFile,
  'NLD': r23 as unknown as RegionFile,
  'NOR': r24 as unknown as RegionFile,
  'POL': r25 as unknown as RegionFile,
  'PRT': r26 as unknown as RegionFile,
  'RUS': r27 as unknown as RegionFile,
  'SWE': r28 as unknown as RegionFile,
  'TUR': r29 as unknown as RegionFile,
  'USA': r30 as unknown as RegionFile,
  'ZAF': r31 as unknown as RegionFile,
};

/** Resolve a country+level to its bundled region file (null if absent). */
export function getRegionFile(cca3: string, level: string): RegionFile | null {
  const key = level === 'departments' ? `${cca3}-departments` : cca3;
  return BUNDLED_REGIONS[key] ?? null;
}
